### ISSUE TITLE
Make the code c++11 compatible

### ISSUE THREAD

**Issue by ilectra** [UCL/research-computing-with-cpp#19]
When I turned on the c++11 flags in cmake, travis started failing, even though everything was working fine on my machine. I had to add -fpermissive for ITK-related stuff to compile, which doesn't fill me with confidence.
We should probably look into getting the correct/latest version of ITK for travis (I tried with libinsighttoolkit4-dev, but it didn't fix the problem), or I don't know what else...

**Comment by MattClarkson** [comment]
Short answer - Im not going to have time to look at this before the lecture now. I can review your notes, but won't be able to fix things like ITK. So, can we just temporarily pull out anything thats not compiling?

**Comment by ilectra** [comment]
Don't worry, there's no rush, it finally compiled with -fpermissive.
I just started this issue as a reminder for us to fix it later.

**Comment by jonc125** [comment]
Did this get fixed last year, or is there still work to be done?

**Comment by MattClarkson** [comment]
I presume nothing got done. But we should review whether or not ITK examples are valid, as only 1 class member does any medical imaging

**Comment by ilectra** [comment]
I didn't follow up since my last message here. But it probably makes sense to remove ITK, like Matt says.
