### ISSUE TITLE
Run tests automatically?

### ISSUE THREAD

**Issue by jonc125** [UCL/research-computing-with-cpp#31]
We currently build our code samples, but don't run any of them. Given that many of them are using Catch to test things, it would probably make sense to run them with ctest, and ideally have travis check that they actually pass!

What do you think @MattClarkson ?

**Comment by MattClarkson** [comment]
Totally agree. We may have had some of that in the past, and then we upgraded a few things, and then in the last minute rush to deliver the lectures, this was the best we could port over. 

I'll do what I can on my notes.
