### ISSUE TITLE
This repo should probably be moved to the UCL-ARC organisation?

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL/research-computing-with-cpp#90]

**Comment by dpshelio** [comment]
Not yet as the `ucl.ac.uk` domain for `ucl-arc` hasn't been still created. We could move it to UCL instead.

**Comment by krishnakumarg1984** [comment]
@dpshelio Would you kindly guide us (perhaps at our next meeting) on how to perform the move to UCL organisation? 

I'd rather deprecate UCL-RITS sooner or later, since this will help the facilitation team to kill off old domains and aid in their migration execise this TI.

**Comment by dpshelio** [comment]
To move to the UCL-ARC.

**Comment by dpshelio** [comment]
Done

**Comment by krishnakumarg1984** [comment]
Thank you!
